config/routes.rb
Rails.application.routes.draw do
 

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  devise_for :users, 
  			 :path => '', 
  			 :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  			 :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  			 				  :registrations => 'registrations'}

  			 resources :users, only: [:index, :show, :edit, :update]
  			 resources :rooms
  			 resources :pictures

  			 resources :rooms do
  			 	resources :reservations, only: [:create]
  			 end 

         resources :conversations, only: [:index, :create] do
          resources :messages, only: [:index, :create]
         end

         resources :rooms do
          resources :reviews, only: [:create, :destroy]
         end 

         get '/preload' => 'reservations#preload'
         get '/preview' => 'reservations#preview'

         get '/your_trips' => 'reservations#your_trips'
         get '/your_reservations' => 'reservations#your_reservations'
         get '/search' => 'static_pages#search'

        post '/notify' => 'reservations#notify'
        post '/your_trips' => 'reservations#your_trips'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable
	validates :fullname, presence: true, length: {maximum: 50}
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
validates :email, presence: true, length:{maximum: 255},
                                  format: {with: VALID_EMAIL_REGEX}
validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :rooms
  has_many :reservations
  has_many :reviews


	  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
          user.fullname = auth.info.name
          user.provider = auth.provider
          user.uid = auth.uid
          user.email = auth.info.email
          user.image = auth.info.image
          user.password = Devise.friendly_token[0,20]
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index  
			@users = User.all
	
	end 


	def show
		@user = User.find(params[:id])
		@rooms = @user.rooms
	end 

	def edit
		@user = User.find(params[:id])
	end 

	def update
			@user = User.find(params[:id])
	     if @user.update(user_params)
	       redirect_to root_path
	     else
	       render 'edit'
	     end
   
	end 


private 
	def admin
		user=User.create(:email =>"werentauser@gmail.com", :password =>"qqqqqq")
		user.admin=true
		user.save!
	end 

	def user_params
    	params.require(:user).permit(:email, :description, :phone_number, :fullname)
  	end

end 

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Edit Profile", edit_user_registration_path(@user), class: "sidebar-link active" %></li>
    </ul>
    <br>
    <%= link_to "View My Profile", user_path(current_user.id), class: "btn btn-default wide" %>
  </div>

  <div class="col-md-9 text-center">
    <div class="panel panel-default">
      <div class="panel-heading">Your Profile</div>  
      <div class="panel-body">
        <div class="container">
          <%= form_for(@user) do |f| %>
            <%= render 'shared/errors' %>

            <div class="form-group">
              <%= f.text_field :fullname, autofocus: true, :placeholder => "Full Name", :class => 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.email_field :email, :placeholder => "Email", :class => 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.text_field :phone_number, :placeholder => "Phone Number", :class => 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.text_area :description, rows: 5, cols: 25,  :placeholder => "Description", :class => 'form-control' %>
            </div>

            <!% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
              <div> <!%= resource.unconfirmed_email %></div>
            <!% end %>

            <div class="form-group">
              <%= f.password_field :password, autocomplete: "off", :placeholder => "New Password (leave blank if you don't want to change it)", :class => 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.password_field :password_confirmation, autocomplete: "off", :placeholder => "Confirm Password", :class => 'form-control' %>
            </div>
            
            <div class="actions">
              <%= f.submit "Save", :class => "btn btn-primary" %>
            </div>

           
          <% end %>
           <div class = "form-group">&nbsp;

          
           <p>Unhappy? <%= button_to "Delete this account", registration_path(@user), :class => "btn btn-danger", data: { confirm: "Are you sure?" }, method: :delete %></p>

    <%= link_to "Back", :back %>
    </div>
        </div>
      </div>
    </div>

  </div>
</div>  

app/views/users/index.html.erb
<% if current_user.try(:admin?) %>
<div class="row"><h1 align = "center">Edit Users</h4></div>
	<% @users.each do |user| %> <br>
		<div class="row">
			<div class="col-md-3">
				<%= image_tag gravatar_url(user), class: 'avatar-full'%>
			</div>

			
			
			<div class="col-md-9">
				<h2><%=link_to user.fullname, user %></h2>

				<div class="description row-space-3">
					<%= user.description %>
				</div>

				
				

			</div>
		</div>
	<% end %>
<% else %>
	<h2>We apologize but you do not have permission to view this page</h2>
<% end %>

app/views/users/show.html.erb
<%provide(:title, "My Profile")%>
<div class="row">
	<div class="col-md-3">
		<div class="center">
			<%= image_tag gravatar_url(@user), class: "avatar-full" %>
			
			<% if current_user != @user %>
				<div class="row-space-2">
					<%= link_to "Send Message", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post', class: "btn btn-primary wide" %>
				</div>
			<% end %>

			<% if current_user.admin && current_user != @user %>
				
					<div class="row-space-2">
						<%= link_to "Edit Profile", edit_user_url(@user), class: "btn btn-primary wide" %>
					</div>
				
			
			<% end %>
			
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">Verification</div>	
			<div class="panel-body">
				Email Address<br>
				Phone Number
			</div>
		</div>
	</div>

	<div class="col-md-9">
		<h2><%= @user.fullname %></h2>

		<div class="description row-space-3">
			<%= @user.description %>
		</div>

		<h4>Listings (<%= @rooms.length %>)</h4><br>

		<div class="row">
			
			<% @rooms.each do |room| %>
				<div class="col-md-4">
					<div class="panel panel-default">
						<div class="panel-heading preview">
							<%= image_tag room.pictures[0].image.url(:medium) %>
						</div>
						<div class="panel-body">
							<%= link_to room.listing_name, room %>
						</div>
					</div>
				</div>
			<% end %>

		</div>

		<h4>Reviews</h4><br>

		<% @rooms.each do |room| %>
			<% if !room.reviews.blank? %>

				<% room.reviews.each do |review| %>
					<div class="row">
						<div class="col-md-2 text-center">
							<%= image_tag gravatar_url(review.user), class: "img-circle avatar-medium" %><br>
							<%= review.user.fullname %>
						</div>
						<div class="col-md-10">
							<%= link_to room.listing_name, room %><br>
							<%= review.comment %><br>
							<%= review.created_at.strftime("%v") %>
						</div>
					</div>
				<% end %>

			<% end %>
		<% end %>

	</div>
</div>